# Generated by Django 2.1.7 on 2019-03-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1400)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='survey',
            name='home',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='survey',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='work',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='questions',
            field=models.ManyToManyField(blank=True, to='apis.Questionaire'),
        ),
        migrations.AddField(
            model_name='survey',
            name='interviewer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apis.Interviewer'),
            preserve_default=False,
        ),
    ]
